version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.3.9-stretch
    steps:
    - run: sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - checkout
    - run: composer validate --strict
    - run: composer install --no-interaction --no-suggest
    - run: composer test
#      - run:
#          name: Run Unit Tests
#          command: |
#            wget -O phpunit https://phar.phpunit.de/phpunit-7.phar
#            chmod +x phpunit
#            sudo mv phpunit /usr/local/bin/
#            ./tests/unit_tests.sh
workflows:
  version: 2
  workflow:
    jobs:
    - test
